export { default as Hero } from "./Hero";
export { default as AppSlider } from "./AppSlider";
export { default as WebsiteSlider } from "./WebsiteSlider";
export { default as NikanOnline } from "./NikanOnline";
export { default as Video } from "./video";
export { default as Reason } from "./reason";
export { default as Steps } from "./steps";
export { default as Nikan } from "./nikan";
export { default as Comments } from "./comments";